### ISSUE TITLE
summary for FLFishery not working

### ISSUE THREAD

**Issue by drfinlayscott** [flr/FLFishery#5]
data(ple4)
flf <- as(ple4, "FLFishery")
summary(flf)
Error in withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning")) : 
  (list) object cannot be coerced to type 'double'
>

**Comment by iagomosqueira** [comment]
Problem was in summary(FLComp). When quant="quant" the output of dims(flf0, used by summary, is a list with two elements called 'quant'. Might have to find a way of making dims and summary more class-specific without having to rewrite the same code for all classes.

Fixed in FLCore commit 5616bb7
